### ISSUE TITLE
Make "Values" section flexbox maintain even rows

### ISSUE THREAD

**Issue by isaiahstjohn** [isaiahstjohn/repyourblock#20]
Petrik suggested yesterday that it would be nice if the values boxes on the home page ("https://repyourblock2020.org/") displayed with the same number of boxes on every line. I suggest we fix this after the website is launched. I don't think it's a high priority issue and we have lots of other important stuff to get done before launch.

Currently, on a large screen, you may see this:

![5 and 1 flexbox flow example](https://user-images.githubusercontent.com/49890287/61319453-404a6200-a7d5-11e9-9a0f-823ab8b08914.PNG)

Or this:
![4 and 2 flexbox flow example](https://user-images.githubusercontent.com/49890287/61319462-43455280-a7d5-11e9-9c03-ad2b270b11c4.PNG)

We want the values boxes to always display on one or more lines such that each line has the same number of items. Since we have six items, they could be displayed in any of the following configurations:

```
| 1 | 2 | 3 | 4 | 5 | 6 |
--
| 1 | 2 | 3 |
| 4 | 5 | 6 |
--
| 1 | 2 |
| 3 | 4 |
| 5 | 6 |
--
| 1 |
| 2 |
| 3 |
| 4 |
| 5 |
| 6 |

```
Probably the easiest solution would be to change to a CSS grid (as @bryce-sampson suggested) and use media queries to change the grid layout according to screen width.

The only downside with using media queries is that it will break if we change the width or number of value boxes, but that shouldn't happen too often.

A more general solution could be created with JavaScript, but I feel like that would be overkill, here.

**Comment by bryce-sampson** [comment]
I agree with this. It is not currently a mandatory change. It works the way
it is and doesn't look bad. So, I'm fine with waiting to change this after
July 31st.

**Comment by isaiahstjohn** [comment]
#29 fixes this issue.
